import Head from 'next/head'
import styles from '../styles/Home.module.css'

// mengambil variabel data
export default function Home({ data }) {
  return (
    <div className={styles.container}>
      <Head>
        <title>Membuat API - Next JS</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>

        {/* fetching data untuk menampilkan di browser*/}
        {data.map((event) => (

          <div key={event.id}>

            <h1>{event.judul}</h1>
            <p>{event.isi}</p>
            <img src={event.banner} alt={event.banner} />

          </div>

        ))}

      </main>

    </div>
  )
}

{/* get server side props */ }
export async function getServerSideProps(context) {

  //membuat function result untuk membaca api localhost
  const result = await fetch("http://localhost:3000/api/blog/read")

  // membuat variabel data untuk mengembalikkan ke dalam bentuk json
  const { data } = await result.json()

  // mengembalikkan properti data untuk memangil variabel data
  return {
    props: {
      data: data
    }
  }

}
